# Generated by Django 2.2.4 on 2019-10-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlgen', '0002_auto_20191024_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
