# Generated by Django 2.2.4 on 2019-10-25 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlgen', '0003_auto_20191025_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='big_url',
            field=models.URLField(validators=[django.core.validators.URLValidator]),
        ),
    ]
