# Generated by Django 2.2.4 on 2019-10-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlgen', '0004_auto_20191025_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='big_url',
            field=models.URLField(),
        ),
    ]
